setwd("C://COURSERA/exploratory_analysis")
con<-file("household_power_consumption.txt")
open(con,"r")
df<-read.csv(con,sep=";")
close(con)
df$Date<-as.Date(df$Date,"%d/%m/%Y")
data<-df[df$Date=="2007-02-01" | df$Date=="2007-02-02",]
library(dplyr)
dataset<-data %>% mutate(Date_Time=paste(Date,Time)) %>% select(Date_Time,Global_active_power:Sub_metering_3)
dataset$Date_Time<-strptime(dataset$Date_Time, "%Y-%m-%d %H:%M:%S")
dataset$Global_active_power<-as.numeric(as.character(dataset$Global_active_power))
setwd("C://COURSERA/exploratory_analysis/ExData_Plotting1")
Sys.setlocale("LC_TIME", "English")
png(file="plot2.png")
plot(dataset$Date_Time,dataset$Global_active_power,type="l",ylab="Global Active Power (kilowatts)",xlab="")
dev.off()