setwd("C://COURSERA/exploratory_analysis")
con<-file("household_power_consumption.txt")
open(con,"r")
df<-read.csv(con,sep=";")
close(con)
df$Date<-as.Date(df$Date,"%d/%m/%Y")
data<-df[df$Date=="2007-02-01" | df$Date=="2007-02-02",]
library(dplyr)
dataset<-data %>% mutate(Date_Time=paste(Date,Time)) %>% select(Date_Time,Global_active_power:Sub_metering_3)
dataset$Date_Time<-strptime(dataset$Date_Time, "%Y-%m-%d %H:%M:%S")
setwd("C://COURSERA/exploratory_analysis/ExData_Plotting1")
Sys.setlocale("LC_TIME", "English")
dataset$Sub_metering_1<-as.numeric(as.character(dataset$Sub_metering_1))
dataset$Sub_metering_2<-as.numeric(as.character(dataset$Sub_metering_2))
png(file="plot3.png")
plot(dataset$Date_Time,dataset$Sub_metering_1,type = "l",xlab="", ylab = "Energy sub metering")
lines(dataset$Date_Time,dataset$Sub_metering_2,col="red")
lines(dataset$Date_Time,dataset$Sub_metering_3,col="blue")
legend("topright",legend=names(dataset[6:8]),lty="solid",col=c("black","red","blue"))
dev.off()